# port
http:
  port: 8080

security:
  jwt:
    # acces token expired in 30s
    accessExp: 60000
    # refresh token expired in 10d
    refreshExp: 864000000
    # secret key, random string
    random: PLkz1SCf5iB4cAum3esWdyv_FFPBHTnvRY

ignoreTokenCheckUrls: 
  - /api
  - /api/auth/login
  - /api/auth/logout
  - /api/auth/register
  - /api/auth/re-gen
  - /api/auth/verify-access-token